package cmd

import (
	"bufio"
	"fmt"
	"github.com/spf13/cobra"
	"gitlab.cosee.biz/pfyl/pfyl-cli/configuration"
	"os"
	"strings"
)

func NewConfigure(config configuration.Configuration) *cobra.Command {
	return &cobra.Command{
		Use:   "configure",
		Short: "configure the pfyl-cli application",
		Run: func(cmd *cobra.Command, args []string) {
			reader := bufio.NewReader(os.Stdin)
			config.ToolChainPath = read(reader, "path to toolchain: ")
			config.ServerAddress = read(reader, "address of pfyl server: ")
			config.AccessToken = read(reader, "access token generated by pfyl server: ")
			err := config.Save()
			if err != nil {
				panic(err)
			}
		},
	}
}

func read(reader *bufio.Reader, question string) string {
	fmt.Print(question)
	answer, err := reader.ReadString('\n')
	if err != nil {
		panic(err)
	}

	return strings.ReplaceAll(answer, "\n", "")
}
